VegPatchDev1/Controllers/GardensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VegPatchDev1;
using VegPatchDev1.Data;
using Microsoft.AspNetCore.Authorization;

namespace VegPatchDev1.Controllers
{
    [Authorize]
    public class GardensController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GardensController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Gardens
        public async Task<IActionResult> Index()
        {
            return View(await(from garden in _context.UserGardens
                              where garden.UserID == User.GetUserId()
                              select garden.ToViewModel(_context.UserPlots.Count((p) => p.GardenID == garden.id))).ToListAsync());
        }

        // GET: Gardens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var garden = await _context.UserGardens
                .SingleOrDefaultAsync(m => m.id == id);
            if (garden == null)
            {
                return NotFound();
            }

            return View(garden);
        }

        // GET: Gardens/Create
        public IActionResult Create()
        {
            ViewData["NameExists"] = false;
            return View();
        }

        // POST: Gardens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,UserID")] Models.GardenShow garden)
        {
            ViewData["NameExists"] = false;
            if (ModelState.IsValid)
            {
                garden.UserID = User.GetUserId();
                if (!garden.CanBeCreated())
                {
                    ViewData["NameExists"] = true;
                    return View(garden);
                }
                _context.Add(garden.ToBase());
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(garden);
        }

        // GET: Gardens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if(!User.UserHasAccessToGarden(id.Value))
            {
                return View();
            }

            var garden = await _context.UserGardens.SingleOrDefaultAsync(m => m.id == id.Value);
            if (garden == null)
            {
                return NotFound();
            }
            return View(garden);
        }

        // POST: Gardens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,UserID")] Models.GardenShow garden)
        {
            if (id != garden.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(garden.ToBase());
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GardenExists(garden.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(garden);
        }

        // GET: Gardens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var garden = await _context.UserGardens
                .SingleOrDefaultAsync(m => m.id == id);
            if (garden == null)
            {
                return NotFound();
            }

            return View(garden.ToViewModel(_context.UserPlots.Count((p) => p.GardenID == garden.id)));
        }

        // POST: Gardens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var garden = await _context.UserGardens.SingleOrDefaultAsync(m => m.id == id);
            _context.UserGardens.Remove(garden);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GardenExists(int id)
        {
            return _context.UserGardens.Any(e => e.id == id);
        }
    }
}

VegPatchDev1/Controllers/PlotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VegPatchDev1;
using VegPatchDev1.Data;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Runtime.CompilerServices;

namespace VegPatchDev1.Controllers
{
    [Authorize]
    public class PlotsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlotsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Plots
        public async Task<IActionResult> Index(int? id)
        {
            string userId = User.GetUserId();
            if (_context.UserGardens.FirstOrDefault((g) => g.UserID.Equals(userId) && (id == null || g.id.Equals(id.Value))) == null)
                return NotFound();
            return View(await (from plot in _context.UserPlots
                               join garden in _context.UserGardens
                               on plot.GardenID equals garden.id
                               join plant in _context.PlantData
                               on plot.PlantID equals plant.id
                               where garden.UserID.Equals(userId) && (id == null || garden.id.Equals(id.Value))
                               select plot.ToViewModel(garden.Name,plant.PlantName)).ToListAsync());
        }

        // GET: Plots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var plotShow = await (from p in _context.UserPlots
                         join garden in _context.UserGardens
                         on p.GardenID equals garden.id
                         join plant in _context.PlantData
                         on p.PlantID equals plant.id
                         where p.id.Equals(id.Value)
                         select new Models.PlotShow(p,garden.Name,plant.PlantName)).SingleOrDefaultAsync();
            if (plotShow == null)
            {
                return NotFound();
            }

            return View(plotShow);
        }

        // GET: Plots/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Plots/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,GardenID,PlantID,PlotArea,StartTime,InitialSeedCount")] Plot plot)
        {
            if (ModelState.IsValid)
            {
                PlotToNotifications(plot).Start();
                _context.Add(plot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new{ id = plot.GardenID });
            }
            return View(plot);
        }

        public async Task PlotToNotifications(Plot p)
        {
            var timerAsync = (from timer in _context.PlantTimers
                          where timer.PlantID.Equals(p.PlantID)
                          select new ValueTuple<PlantTimers, Plot>(timer, p)).ToListAsync();
            var alarmAsync = (from alarm in _context.PlantAlarms
                          where alarm.PlantID.Equals(p.PlantID)
                          select new ValueTuple<PlantAlarms, Plot>(alarm, p)).ToListAsync();

            Task.WaitAll(timerAsync, alarmAsync);

            Task.Run(() => NotificationHandler.timers.ScheduleRange(timerAsync));
            Task.Run(() => NotificationHandler.alarms.ScheduleRange(alarmAsync));
        }

        // GET: Plots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.UserPlots.SingleOrDefaultAsync(m => m.id == id);
            if (plot == null && User.UserHasAccessToPlot(plot.id))
            {
                return NotFound();
            }
            return View(plot);
        }

        // POST: Plots/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,GardenID,PlantID,PlotArea,StartTime,InitialSeedCount")] Plot plot)
        {
            if (id != plot.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (User.UserHasAccessToPlot(plot.id))
                    {
                        _context.Update(plot);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlotExists(plot.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = plot.GardenID });
            }
            return View(plot);
        }

        // GET: Plots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.UserPlots
                .SingleOrDefaultAsync(m => m.id == id);
            if (plot == null)
            {
                return NotFound();
            }

            return View(plot);
        }

        // POST: Plots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plot = await _context.UserPlots.SingleOrDefaultAsync(m => m.id == id);
            if (User.UserHasAccessToPlot(id))
            {
                _context.UserPlots.Remove(plot);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool PlotExists(int id)
        {
            return _context.UserPlots.Any(e => e.id == id);
        }
    }
}

VegPatchDev1/Views/Gardens/Create.cshtml
@model VegPatchDev1.Garden

@{
    ViewData["Title"] = "Create";
    bool? nameExists = (bool?) ViewData["NameExists"];
}

<h2>Create</h2>

<h4>Garden</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <desc asp-for="Name"></desc>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger">@if (nameExists != null && nameExists.Value) { <span> Garden name already in use for this account. </span> }</span>
            </div>
            <input type="hidden" asp-for="UserID" value="id"/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VegPatchDev1/Views/Gardens/Delete.cshtml
@model VegPatchDev1.Models.GardenShow

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Garden</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlotCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlotCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VegPatchDev1/Views/Gardens/Details.cshtml
@model VegPatchDev1.Models.GardenShow

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Garden</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlotCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlotCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VegPatchDev1/Views/Gardens/Edit.cshtml
@model VegPatchDev1.Garden

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Garden</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserID" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VegPatchDev1/Views/Gardens/Index.cshtml
@model IEnumerable<VegPatchDev1.Models.GardenShow>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlotCount)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlotCount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-controller="Plots" asp-action="Index" asp-route-id="@item.id">Plots</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>